In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from ydata_profiling import ProfileReport
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder,OrdinalEncoder
import warnings
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
import pickle
from sklearn.pipeline import Pipeline
%matplotlib inline
warnings.filterwarnings('ignore')

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
data=pd.read_csv('Raisin_Dataset.csv')

In [9]:
data.info

<bound method DataFrame.info of                                                   Area  MajorAxisLength  \
0                                                87524       442.246011
1                                                75166       406.690687
2                                                90856       442.267048
3                                                45928       286.540559
4                                                79408       352.190770
..                                                 ...              ...
896                                              87350       440.735698
897                                              99657       431.706981
898                                              93523       476.344094
899                                              85609       512.081774
900  Citation Request :\nCINAR I., KOKLU M. and TAS...              NaN

     MinorAxisLength  Eccentricity  ConvexArea    Extent  Perimeter    Class
0         253.291155      0.819738     90546.0  0.758651   1184.040  Kecimen
1         243.032436      0.801805     78789.0  0.684130   1121.786  Kecimen
2         266.328318      0.798354     93717.0  0.637613   1208.575  Kecimen
3         208.760042      0.684989     47336.0  0.699599    844.162  Kecimen
4         290.827533      0.564011     81463.0  0.792772   1073.251  Kecimen
..               ...           ...         ...       ...        ...      ...
896       259.293149      0.808629     90899.0  0.636476   1214.252    Besni
897       298.837323      0.721684    106264.0  0.741099   1292.828    Besni
898       254.176054      0.845739     97653.0  0.658798   1258.548    Besni
899       215.271976      0.907345     89197.0  0.632020   1272.862    Besni
900              NaN           NaN         NaN       NaN        NaN      NaN

[901 rows x 8 columns]>

In [7]:
data.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
0,87524,442.246011,253.291155,0.819738,90546.0,0.758651,1184.040,Kecimen
1,75166,406.690687,243.032436,0.801805,78789.0,0.684130,1121.786,Kecimen
2,90856,442.267048,266.328318,0.798354,93717.0,0.637613,1208.575,Kecimen
3,45928,286.540559,208.760042,0.684989,47336.0,0.699599,844.162,Kecimen
4,79408,352.190770,290.827533,0.564011,81463.0,0.792772,1073.251,Kecimen

In [8]:
data.describe()

,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter
count,900.000000,900.000000,900.000000,900.000000,900.000000,900.000000
mean,430.929950,254.488133,0.781542,91186.090000,0.699508,1165.906636
std,116.035121,49.988902,0.090318,40769.290132,0.053468,273.764315
min,225.629541,143.710872,0.348730,26139.000000,0.379856,619.074000
25%,345.442898,219.111126,0.741766,61513.250000,0.670869,966.410750
50%,407.803951,247.848409,0.798846,81651.000000,0.707367,1119.509000
75%,494.187014,279.888575,0.842571,108375.750000,0.734991,1308.389750
max,997.291941,492.275279,0.962124,278217.000000,0.835455,2697.753000